trigger:
  branches:
    include:
      - main
  paths:
    include:
      - apps/worker/**
      - pipelines/Service-CI/CI-Worker-Pipeline.yml

variables:
  pythonVersion: "3.12"
  imageRepository: "vishwakarmaritesh08/taskforge-worker"
  imageTag: "v1"

stages:
  - stage: Worker_CI
    displayName: Build, Test, Package Worker
    jobs:
      - job: Build_Test_Package
        displayName: Worker CI
        pool:
          name: taskforge-local-pool

        steps:
          - checkout: self

          - script: |
              python3 -m pip install --upgrade pip
              pip3 install -r apps/worker/requirements.txt
              ruff check apps/worker/src
              pytest apps/worker/src/tests
            displayName: Install dependencies, lint, and test worker

          - script: |
              docker build -t taskforge/worker:v1 apps/worker
              docker tag taskforge/worker:v1 $(imageRepository):$(imageTag)
              docker push $(imageRepository):$(imageTag)
            displayName: Build and push worker Docker image