apiVersion: v1
kind: ConfigMap
metadata:
  name: taskforge-config
  namespace: devops-challenge
  labels:
    app.kubernetes.io/name: taskforge-config
    app.kubernetes.io/part-of: taskforge
data:
  APP_ENV: "local-kind"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskforge"
  DB_CONNECT_TIMEOUT_SECONDS: "3"
  POLL_INTERVAL_SECONDS: "10"
  WORKER_BATCH_SIZE: "5"
