apiVersion: v1
kind: Secret
metadata:
  name: taskforge-secret
  namespace: devops-challenge
  labels:
    app.kubernetes.io/name: taskforge-secret
    app.kubernetes.io/part-of: taskforge
type: Opaque
stringData:
  POSTGRES_USER: "taskforge_user"
  POSTGRES_PASSWORD: "taskforge_password"

